# Generated by Django 4.1.1 on 2022-10-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
